# Command-line tools
brew "aws-iam-authenticator"
brew "awscli"
brew "bash"
brew "fzf"
brew "gh"
brew "git"
brew "gnupg"
brew "go"
brew "herdr"
brew "hunk"
brew "jq"
brew "neovim"
brew "poetry"
brew "protobuf"
brew "pyenv"
brew "ripgrep"
brew "sheldon"
brew "yazi"
brew "zsh"

# Desktop and developer apps
cask "gcloud-cli"
cask "firefox"
cask "ghostty"
cask "gpg-suite"
cask "hammerspoon"
cask "intellij-idea"
cask "karabiner-elements"
cask "mitmproxy"
cask "rectangle"
cask "slack"
cask "zoom"
cask "mos"
cask "docker"
