shell = "zsh"

[plugins]
[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
[plugins.z]
github = "agkozak/zsh-z"
